services:
  - type: web
    name: storefront
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn storefront.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: storefront.settings.production
